name: Build TrollChat IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y clang ldid make zstd zsign git curl zip

    - name: Download llama.cpp and model
      run: |
        git clone https://github.com/ggerganov/llama.cpp src/llama
        curl -L -o src/models/tinyllama.gguf https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf

    - name: Build app binary
      run: |
        cd src
        make

    - name: Prepare .app bundle
      run: |
        mkdir -p TrollChat.app/models
        cp src/trollchat TrollChat.app/TrollChat
        cp trollchat.plist TrollChat.app/Info.plist
        cp entitlements/trollchat.entitlements entitlements.plist
        cp src/models/tinyllama.gguf TrollChat.app/models/

    - name: Code-sign binary with ldid
      run: |
        ldid -S entitlements.plist TrollChat.app/TrollChat

    - name: Package .ipa
      run: |
        mkdir Payload
        mv TrollChat.app Payload/
        zip -r trollchat.ipa Payload

    - name: Upload .ipa
      uses: actions/upload-artifact@v4
      with:
        name: trollchat.ipa
        path: trollchat.ipa
